apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVVUJGelBZa1dLKy9aYXUxSHFhK3kxS
EdrUWI0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSTJNRFV3TkRFeE1UQXdOMW9YRFRNMgpNRFV3TV
RFeE1UQXdOMW93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzTGxjN1J
Eb1IrWGE2ZmNWcWozZVZZYXBJT0Y1WjhteGNuTzMKaTJYQk9PUk5lK0tGNENCNGtNeElIc2FlUFN6NUZlcG02enBueDdLTHhWTHdBWGk5OFBRbzFhRFhVTi9wSGlZ
OQowR2NYNndYOFRQWHN5N0YybHFVaXdhVm5QTnVEZGU3WEZqSEhXNDNhL3lBRlM3ZUthSitWMy84UUsvSlZmMmQyCll2Rzl3WkhFajJkWk9va0VYK1BjVURqaGxic
WRMUU5DakVsRllsZ2ErOFVsT0ZwYUkxa3JhR3JOMFowc2o5Z3IKUEVJdlNxTXIvV0tCRkxqQ1ZSaFFTM1ByRFowNW5neEJsNXVnRjJBa0lTM0dhdC91L3Vwd0Vjdk
N3ZE90RlkrUwpHNndBSnB6bW9jTjdoa3N6SVRIb0lXWlJRYWFjZzdRZmFrSm9yQWpHbzlDekFBYlp4d0lEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVW9ZOENlKzR
4b09FRnluYm1zVU5hem03Mjdld3dId1lEVlIwakJCZ3dGb0FVb1k4Q2UrNHgKb09FRnluYm1zVU5hem03Mjdld3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2tx
aGtpRzl3MEJBUXNGQUFPQwpBUUVBYUdBK29STERXajhkTUJOSlFjM1VpazJ5NGQrNmc4TkR3SWhjdFZEWlpQL3VyOVhtSXg3V2NWTFZCcE1YCm1YOTVGakpQbFNWO
HIwUjFDbnEyaUF2Zm5saXhYL2J3VFBVR3ZkZmFyV0ErZUlxNk1mQklxdTR3eis5SUlvMy8KRjZqU00rdlB5Yi9lblZiT0pDVzlrdDdmSUpzYkNUN1cxK0QrZnZ3Zm
YwRGFPNXpQN2dNd1ZGQ0ozbUYzOFcydQpFdHNNUDRMREIyWlRLTkdjMU80U1pWZlBMY1hpL2prSTdzSEpZT2FNbENuQll6b1hSY205Sm5iRVRxV0FwZmFTCmtOaWZ
vT29oNlRBSk1hR29LV3RDdGxXSXZMYmFMMWVySytQQnZGTzdyMEtPdUtJVGh2VVB6QlhuSWc2OU1mTVgKelJoZ3hPL3ZaQVZTNkM1WTBobExZSElPZlE9PQotLS0t
LUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://44.200.74.6:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN4ekNDQWE4Q0ZDZnc2Q1l2d2FPVjBZZzF4bFhZdFNyWmhWb3ZNQTBH
Q1NxR1NJYjNEUUVCQ3dVQU1CY3gKRlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQWVGdzB5TmpBMU1EUXhNVEV3TURsYUZ3MHpOakExTURFeApNVEV3TURsY
U1Da3hEakFNQmdOVkJBTU1CV0ZrYldsdU1SY3dGUVlEVlFRS0RBNXplWE4wWlcwNmJXRnpkR1Z5CmN6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0
FRb0NnZ0VCQUw5Q0czNDhFVHNZKytxSjBOVjMKQ1Q3WHNmTU5OZzNJL045Z2hDZjhBVlp0aGV5MHBBUTZhMlRDalpNYzIvVlRPTzVBcE5sYjhjMXRMckE5Ky94TQp
LZHFGRDdpV1V4eCtDcnZBR1VDMHFKRDViSWlVU2VjMEN5V0tMMHEycmpNTEdPWU03V2JLZzNaYzJpa1pSOVFLCnlNMVBkalRTRUszYURUcmt3aXB5Sk4wV1NHeVhM
S0F6dzc4YThzWDVsQndvRDI4bGw3dWhneWdRc3YydmdyR1QKY1A4aWpGQ1A4WEFIc1Zna1VscEFJaWlaWFozTHplTmI1b0t3dEFLbVdnOGlTQ1FDUWxKYW1KQ1d0S
kdYTVl5Ywpnb2xJVFRxdnpYVklSZ2FTOG9ZZkVXUGQrQkJ6Q1JWdjV0Z25FaU1UK2VOMitDVlJDbzBIbzNBVUhaOXVhUTltClh4VUNBd0VBQVRBTkJna3Foa2lHOX
cwQkFRc0ZBQU9DQVFFQTE2QmorRWtGdkVsUm5uSFpmeVVIQ3FUU01VY3QKMlY4Q1BNWnpiSUZuV2F2NlJ3ZmJXejlsak5MVlNydVhrVVVScUppQU4wRkpBUXZSS3M
3TGtERVJXOGs1THFBcgpIcEFjRWpaOEtQT0Z3NnlrdU55RFBxdFArRTRIbjZUcTI5bEt0TzVTRFl5ak9wRGsrdXVVeGs4dmZ6eG1DbmJSCnpGVXkvS3E1bXJEQ29p
YVpjSFVKeFFjeG1wQTg4S3lBeWZKZHpJTTNtT3docDhDcndEK0xBZFZvTjBFZUtIWnQKY3dpcm1XeU5DRXhPMnFlV1U4b0hORkNCM0lOSHVTWUhjS3FscXl6NERaM
jVuVUpGaU5OWFRvTlM5R2RxU0Y5QQpia3BJNUdFenpMZjFTN0p0YytMaURsdkdKcUhZdmgyajBmcUtpczNJY2VmRFdEKzJaSE5DWUF4b0dBPT0KLS0tLS1FTkQgQ0
VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV1d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktVd2dnU2hBZ0VBQW9JQkFR
Qy9RaHQrUEJFN0dQdnEKaWREVmR3aysxN0h6RFRZTnlQemZZSVFuL0FGV2JZWHN0S1FFT210a3dvMlRITnYxVXpqdVFLVFpXL0hOYlM2dwpQZnY4VENuYWhRKzRsb
E1jZmdxN3dCbEF0S2lRK1d5SWxFbm5OQXNsaWk5S3RxNHpDeGptRE8xbXlvTjJYTm9wCkdVZlVDc2pOVDNZMDBoQ3QyZzA2NU1JcWNpVGRGa2hzbHl5Z004Ty9Hdk
xGK1pRY0tBOXZKWmU3b1lNb0VMTDkKcjRLeGszRC9Jb3hRai9Gd0I3RllKRkphUUNJb21WMmR5ODNqVythQ3NMUUNwbG9QSWtna0FrSlNXcGlRbHJTUgpsekdNbkl
LSlNFMDZyODExU0VZR2t2S0dIeEZqM2ZnUWN3a1ZiK2JZSnhJakUvbmpkdmdsVVFxTkI2TndGQjJmCmJta1BabDhWQWdNQkFBRUNnZ0VBQnNET1c4K29weGhsU3Ix
UGd6NE5aOTZ4d1B5QWxTZUdScWZpN2VoTXlHUWMKVVI1Z1ZzK3VRZnBKb3lSbkV0dHUzSWNxR3ZMY05qUlhYNG1mOUdNdGVWa0lWQi9Bc3dNQUhSOGNRZlN2RUFmT
QpMVkNaR3RUWjlCc2cxTnJmdmFqQXpVTVZmZG1EYkJ2V3RNVkx6QWRCcDR0bUxqK1QvQmEweVdJM3VSamJMaEE0CnBTV1owRjVrRXIxdHFtVFV2cjN0cDl5UW9NYW
JidTY2ZzlFQzNDT21ORlM3Q2syZC9PL3JhWDdtSjJUMGsrMU8KbUR6OHppaGxEcEkwVHhWU2hMMHErMEdHcmdxcldRY0pwMkx0Rmp5SDcySnJsajNEVUNUTlZnbzR
zd3FNUXBKeQpoOFdNWklFWXp5U29NNGMvWXl2WUhlT0VrTFZUMm14UDRXNmtUVzBDVVFLQmdRRDhmZ0E2MmtqMTJUbXFyOGxMCkRNUlV0bTZQMVBEeXFwSzlLb0VD
R0FRVW5uTWxxWlh6TXZLV3JIMVpZS3hDelBCMkxRL3diK2I4S3ViLzIrNk8Kd2c0aGdJVC80VGhlSnlqSHAyZGN3NUswYmw2MzE4cUtqcENhd2tYbmFzM1BtR09ta
lVsczhTOFQxd3JiY051VApRU0hTbmF0UWFtMUIwc1o3ZEcyb3RZS3NFUUtCZ1FEQjZsTkowSThqYSthYUtrSExLQ0VKaDJabWdDa3FSVU9GCllJak9OaFR3bzRNUj
NOKzdHbXFJR05qUGptcVBzN0JIMU9CMHhsaGE0ak1YTndiVHRTWUQ0emRPSGVjRDhiaEgKN1IxOGhOaEtlTmRNd0huc2FxZ3NFL3BCZFFWWDg1ZEZCcHV6RjFsOHh
UM2xKMHNJMkw5T25SbVdnb2VsSkY0egpIcU5CWHFhV3hRSi9VT0FMTXM2NGtBY0VjYWZjMGkxRXRkMjVqRmlvMVJITjdzbXVpUDBvVVhKdmI2RGlad1BxCnNGaVB6
aEVwSER5SXlWR2x5VjRPbnJjZlJ0VXJsSTZUK0NjeWNzT3hTbmRBbUxNR2FMQThUWThNeDlaWENncWcKUnZIemNpekR2N3NRTUVrUk85UUZRRldoSktrQnJDa3dyR
VhVbWUxOUVaaHgreGxRQnJvZElRS0JnRVlJai80SApzYnAwUEx1TzZXWXEzd3VtK0FlcTM3TWhnc3BIM0FERnJYaGZSWFlORkV4cHRQSGtMMkYrcU9PdlhNb0Vpdk
FCCnRtVlVibWxDK1ZjNmhEbEJOWGNqKzR3RUg2N3lad1RTb1o3NzE1NGpvYVVOdkNEM01obXozck11Q1lMbmFSSWMKSzdpUkw5SjBCM2h4ZDE0NEJNYkQ2Nk5yNkE
yRVVpZkl2RmVWQW9HQkFKVHl0T2tLcndhRDgvN0xHRTdaY1RGcApnbW9Fa01TL3dReGp5bUd3RHZjY2YwZ2xhWkNLMk9nRk9Wck1scS9DWGhrYVp2SHEzZWZKRTls
Vi9NRk4zbGd5CnhTVFlmSkw1NWNyZ29POExzNU5PSHlGb3Q3alBhTG5NaVZHMTBhcVJjRG5sZExrQWtPdlFsUXlHVmE0aUM4NFIKQk1ocVdPRExDVVZ2Q2V6clhsR
zAKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=