global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ec2-nodes'
    static_configs:
      - targets: ['34.205.225.101:9100']
        labels:
          service_name: 'Worker-Node-1'
          env: 'production'
      - targets: ['18.234.219.40:9100']
        labels:
          service_name: 'Worker-Node-2'
          env: 'production'
      - targets: ['44.204.26.141:9100']
        labels:
          service_name: 'Worker-Node-3'
          env: 'production'
      - targets: ['13.218.117.158:9100']
        labels:
          service_name: 'Worker-Node-4'
          env: 'production'
      - targets: ['100.25.246.38:9100']
        labels:
          service_name: 'Controller-Node'
          env: 'production'
