apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
  labels:
    app: rabbitmq
    project: microservices_mp4-to-mp3-converter
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/data/rabbitmq
